Completed css-brochure-form exercise
wang-morris/m1-0522-code-solutions pull request #16
Opened 2022-05-20 04:05 UTC by wang-morris

![Screen Shot 2022-05-19 at 9 04 54 PM](https://user-images.githubusercontent.com/103090771/169448269-a0fbf80d-2479-4401-b655-ccc71de07897.png)

2022-05-20 04:08 UTC, scrumptiousdev commented on css-brochure-form/index.html
> +        <label for="dropdown">HOW MANY ENGINEERS ARE YOU HIRING IN THE NEXT 6 MONTHS?</label>
Any thought on `for` attribute value?

2022-05-20 04:09 UTC, Zhiwutian requested changes
Looking good overall! make sure to add the border around the inputs to match the example, and update based on the other feedback given. Reach out if you have questions!

2022-05-20 04:09 UTC, Zhiwutian commented on css-brochure-form/styles.css
> +  padding: 8px 300px 8px 8px;
try to avoid using large amount of padding like this.

2022-05-20 04:09 UTC, Zhiwutian commented on css-brochure-form/styles.css
> +  padding: 8px 270px 8px 8px;
same as below

2022-05-20 04:09 UTC, Zhiwutian commented on css-brochure-form/index.html
> +  <h1>LEARN MORE</h1>
I would wrap all of the content in a `container` element with a set width and then center that on the page.

2022-05-20 04:16 UTC, scrumptiousdev commented on css-brochure-form/styles.css
> +  margin-left: 345px;
After [wrapping with `.container`,](https://github.com/wang-morris/m1-0522-code-solutions/pull/16/files#r877713872) try not to use `margin-left` to have button aligned to the right

2022-05-20 22:49 UTC, wang-morris commented
<img width="865" alt="Screen Shot 2022-05-20 at 3 19 28 PM" src="https://user-images.githubusercontent.com/103090771/169621849-0c4613b3-9fe7-4d83-8937-4fbd85501041.png">

2022-05-23 16:22 UTC, Zhiwutian approved these changes
👍🏼

2022-05-23 20:41 UTC, merged